### ISSUE TITLE
Add maintainers from community

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchainjs#1]
- Embedchain team will develop the feature first in Python and then port it to Javascript. So javascript sdk will be lagging in terms of features, but want to keep this gap as minimum as possible.
- Community is asking to be added as moderators
    - [cachho](https://discord.com/channels/1121119078191480945/1121119078858358846/1125516888370331758)
    - [Papa Dosa](https://discord.com/channels/1121119078191480945/1121119078858358846/1125491924820840518)

Community asks / features to add
- typescript support
- support for youtube loader

**Comment by cachho** [comment]
@cachho added as maintainer as #4
