### ISSUE TITLE
naval_chat_bot.add limitations

### ISSUE THREAD

**Issue by itorian** [embedchain/embedchainjs#10]
This project looks interesting, i have few quick question.
consider we have thousands of PDF files, URLs and videos, what are the limitations on the adding data set? is is required to naval_chat_bot.add all thousands of resources every time app inits ?

**Comment by itorian** [comment]
Hey @cachho,
Thank you so much for your reply.
(1) No, you should split into a training and a chat/query script... how? any documentation about it?
(2) What else do you recommend (with documentation) for working with large data set (thousands of PDF files, URLs and videos)?

**Comment by taranjeet** [comment]
I think we should do it this way
• have a local db (sqllite) which maintains a mapping of what all urls/data sets have been indexed. if a doc is indexed we can skip chunking/embeddding process for it. the only problem that we will have is for data sets where the contents changes (like web page). Maybe this logic can be data set specific
• we might need to give another db. What are you planning to use / using? @itorian?

**Comment by itorian** [comment]
Hi @taranjeet,
Appreciate your response.
We are planning to build and SaaS-ify a secure, better, scalable, low cost enterprise knowledge search engine for enterprise customers having a large data set. The question we have is:
(1) Fine-tuning or embedding
(2) LangChain (Python/JS) or Microsoft's Semantic Kernel (any language)
Happy to discuss this further.

**Comment by cachho** [comment]
> (1) No, you should split into a training and a chat/query script... how? any documentation about it?

You just create on script that only uses the `add` method. It populates the database. Give it time, this process is asyncronous.

Then you create a second script that just uses the `query` method. That's the script for the end user. 

> (2) What else do you recommend (with documentation) for working with large data set (thousands of PDF files, URLs and videos)?

It works just fine for me, out of the box.

**Comment by cachho** [comment]
It seems like there are no open questions, closing this.
