### ISSUE TITLE
[FEATURE] Reset function

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchainjs#8]
Since this package is in client-mode, we need a function to reset the chroma db. Otherwise, you have to go into the docker container, and delete the files, which is a mess.

**Comment by AbrahimZaman360** [comment]
> Since this package is in client-mode, we need a function to reset the chroma db. Otherwise, you have to go into the docker container, and delete the files, which is a mess. 

Create a Function Called ResetVDB then use os module to delete the store and it will create automatically next time anything is added.

**Comment by cachho** [comment]
> > Since this package is in client-mode, we need a function to reset the chroma db. Otherwise, you have to go into the docker container, and delete the files, which is a mess.
> 
> Create a Function Called ResetVDB then use os module to delete the store and it will create automatically next time anything is added.

hey, this has been resolved for a while, using the .reset() method.
